// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs-nORS0-_xEH7xSPvWHqDOnu3U9aG5vs',
    appId: '1:231095125934:web:124530260a823461afea3f',
    messagingSenderId: '231095125934',
    projectId: 'mpcalcu',
    authDomain: 'mpcalcu.firebaseapp.com',
    storageBucket: 'mpcalcu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAckOso4GC8G0L4qUghBJbScjuZI4buf9I',
    appId: '1:231095125934:android:02fa522e22cd3499afea3f',
    messagingSenderId: '231095125934',
    projectId: 'mpcalcu',
    storageBucket: 'mpcalcu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtBzo6MYQ-quwi8cB3RWnnKY3peAiv4H0',
    appId: '1:231095125934:ios:57689789950a1c47afea3f',
    messagingSenderId: '231095125934',
    projectId: 'mpcalcu',
    storageBucket: 'mpcalcu.appspot.com',
    iosClientId: '231095125934-3849jfn1qhgr1damnvc0qij3pmevqgkg.apps.googleusercontent.com',
    iosBundleId: 'com.g4g.mpcalcu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtBzo6MYQ-quwi8cB3RWnnKY3peAiv4H0',
    appId: '1:231095125934:ios:010f4a11253e5c8fafea3f',
    messagingSenderId: '231095125934',
    projectId: 'mpcalcu',
    storageBucket: 'mpcalcu.appspot.com',
    iosClientId: '231095125934-rhs23cjrehfle5grtk1l1en61iaotma2.apps.googleusercontent.com',
    iosBundleId: 'com.g4g.mpcalcu.RunnerTests',
  );
}
